steps:
  # Construir a imagem do container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crm-arduus', '.']
  
  # Enviar a imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crm-arduus']
  
  # Implantar a imagem no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-arduus'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-arduus'
      - '--platform'
      - 'managed'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

# Imagens a serem armazenadas no Container Registry
images:
  - 'gcr.io/$PROJECT_ID/crm-arduus'

# Tempo limite para a construção (em segundos)
timeout: '1800s'  # 30 minutos 